import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
page.on('console', m => console.log('CONSOLE[' + m.type() + ']:', m.text().slice(0, 200)));
page.on('requestfailed', r => console.log('REQFAIL:', r.url().slice(0, 80), r.failure()?.errorText));
await page.goto('file:///home/user/curve-studio-standalone.html', { waitUntil: 'load' });
await page.waitForTimeout(1500);
console.log('ctx:', await page.evaluate(() => typeof window.__ctx));
console.log('topbar:', await page.evaluate(() => document.getElementById('topbar').innerHTML.length));
await browser.close(); process.exit(0);
